// <auto-generated />
using System;
using HelpDeskSystem.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDeskSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDeskSystem.API.Models.CalledModel", b =>
                {
                    b.Property<int>("IdCalled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCalled"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateClose")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Technical")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TechnicalId")
                        .HasColumnType("integer");

                    b.HasKey("IdCalled");

                    b.HasIndex("ClientId");

                    b.ToTable("tb_Calleds", (string)null);
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.ClientModel", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdClient"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumberClient")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdClient");

                    b.ToTable("tb_Clients", (string)null);
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.MessageModel", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<int>("CalledId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("DateHours")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Origin")
                        .HasColumnType("integer");

                    b.HasKey("IdMessage");

                    b.HasIndex("CalledId");

                    b.ToTable("tb_Messages", (string)null);
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.CalledModel", b =>
                {
                    b.HasOne("HelpDeskSystem.API.Models.ClientModel", "Client")
                        .WithMany("Calleds")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.MessageModel", b =>
                {
                    b.HasOne("HelpDeskSystem.API.Models.CalledModel", "Called")
                        .WithMany("Messages")
                        .HasForeignKey("CalledId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Called");
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.CalledModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("HelpDeskSystem.API.Models.ClientModel", b =>
                {
                    b.Navigation("Calleds");
                });
#pragma warning restore 612, 618
        }
    }
}
